### ISSUE TITLE
Feature Request: ReportOutputPath for `ue4 test`

### ISSUE THREAD

**Issue by TBBle** [adamrehn/ue4cli#11]
The UE4 Automation Tests can write out a JSON results file when the command-line `-ReportOutputPath` is provided.

However, the command-line processing for `ue4 test` puts all arguments inside the `"RunTests Now "` argument, so we can't trivially append `-ReportOutputPath` to the `ue4 test` call as we do with `ue4 package` for example.

Since we already provide flags that aren't what the internal command-line uses (i.e. `--all` and `--filter`, then simply supporting something like `--reportOutputPath` would be reasonable.

If it's helpful, I noticed an example of the `index.json` output file at https://www.emidee.net/ue4/2018/11/13/UE4-Unit-Tests-in-Jenkins.html.

**Comment by adamrehn** [comment]
Apologies for the delay in responding to this, it's been a busy week.

Rather than add explicit support for a specific argument, I've added support in commit 59a1b62 for passing arbitrary arguments using the syntax `ue4 test TEST1 TEST2 TESTN -- ARG1 ARG2 ARGN`. Could you please give that a go and let me know if you encounter any issues? (Be gentle when passing arguments with special characters under Windows though, since I have to format the generated command-line as a string for compatibility with old, buggy versions of UE4 and my current escaping implementation [is not exactly stellar](https://github.com/adamrehn/ue4cli/blob/v0.0.34/ue4cli/Utility.py#L62-L69).)

**Comment by TBBle** [comment]
Sorry for the delay. Just an update to say I haven't had a chance to test this yet, but hope to this week. I see it's not in a release yet, so I assume it'll work if I test with `pip install some-github-URL`.

**Comment by adamrehn** [comment]
This is now in release 0.0.35, so you can use that for performing testing.

**Comment by TBBle** [comment]
Appears to be working correctly now, as-of 0.0.35. Before we got back to reintegrating `-ReportOutputPath`, we found we had another use-case for extra arguments, so the `--` separator approach was an excellent choice.
