### ISSUE TITLE
-VS2019 Optional Argument needs to be earlier

### ISSUE THREAD

**Issue by CanisHelix** [adamrehn/ue4cli#35]
Passing in the optional argument -VS2019 as per `ue4 package Development -VS2019` results in errors that VS2017 doesn't exist. Running RunUAT also produces this error unless -VS2019 is just after BuildPlugin arg but before the Plugin/Package paraments.

**Comment by CanisHelix** [comment]
The same applies to -TargetPlatforms too. I was only to get this working with UE 4.26.2 by forcing those into https://github.com/adamrehn/ue4cli/blob/master/ue4cli/UnrealManagerBase.py#L439 after BuildPlugin. Not ideal, but a hack that worked.

**Comment by TBBle** [comment]
I can't see in [the UE4 code](https://github.com/EpicGames/UnrealEngine/blob/4.26/Engine/Source/Programs/AutomationTool/Scripts/BuildPluginCommand.Automation.cs) _why_ this is the case, it actually parses the args in the order currently used, and unlike in the C++ code, it's not consuming the args as it parses them.

Like #32, the fix is possibly just to rearrange that line to include `extraArgs` between `'BuildPlugin'` and `'-Plugin='`.

However, it might also indicate that something is wrong in how we're gathering those args. Perhaps try setting the env-var `UE4CLI_VERBOSE` to 1, and see what is [actually being passed to `subprocess.call`](https://github.com/adamrehn/ue4cli/blob/v0.0.52/ue4cli/Utility.py#L141-L143), to rule out some bug elsewhere in the pipeline.

**Comment by CanisHelix** [comment]
That actually works for both and tested on Win/Linux/Mac too. I think this is a RunUAT issue as even passing in the "wrong" order there causes the same issue. I'll put a PR in similar to #32
